### ISSUE TITLE
add more awesome profile ❤

### ISSUE THREAD

**Issue by yezz123** [abhisheknaiidu/awesome-github-profile-readme#196]
More sweet profile and awesome code ❤✌

**Comment by abhisheknaiidu** [comment]
@yezz123 Just now merged 35 profile readmes 😅

**Comment by niveshbirangal** [comment]
@AbhishekMaira10 What's the criteria for getting featured?
I would love to get featured in this wonderful repository

**Comment by AbhishekMaira10** [comment]
Nothing specific. You just need to have a unique profile with good features and you can contribute.

**Comment by WarenGonzaga** [comment]
Hi @abhisheknaiidu add mine too and others waiting on PR

**Comment by akshitagupta15june** [comment]
@abhisheknaiidu have a look at my PR for my dynamic profile https://github.com/akshitagupta15june/akshitagupta15june

**Comment by SoorajSNBlaze333** [comment]
@abhisheknaiidu could you please take a look at the PR's raised to get featured. Mine is here https://github.com/abhisheknaiidu/awesome-github-profile-readme/pull/327
