### ISSUE TITLE
Feature:  Build Pages for this Repo？

### ISSUE THREAD

**Issue by Xunzhuo** [abhisheknaiidu/awesome-github-profile-readme#213]
### Is your feature request related to a problem? Please describe.

If more and more Profiles added in this Repo, Readme will be so long and hard to find  and  search.

### Describe the solution you'd like

Maybe Build a Pages for this? More friendly and more continuous

**Comment by abhisheknaiidu** [comment]
@Xunzhuo Yes, you're right! that's why we have our site https://zzetao.github.io/awesome-github-profile/

It uses GH Actions, to fetch every data in every 15 min.

**Comment by Xunzhuo** [comment]
OK~
