### ISSUE TITLE
Feature: Should the profile names be sorted alphabetically?

### ISSUE THREAD

**Issue by rusty-sj** [abhisheknaiidu/awesome-github-profile-readme#244]
### Is your feature request related to a problem? Please describe.

The profile names are being added very randomly right now. Should we make them alphabetical so as to maintain order?

### Describe the solution you'd like

- Keep all the names alphabetically sorted
- Ask people to add their names in a sorted order before creating a pull request

### Additional context

Just a suggestion; it might be least significant

**Comment by jeferson0993** [comment]
good sugestion. I was thinking about the same thing, lol

**Comment by ABSphreak** [comment]
Well, now it has grown to a point where we would have to do something like that to better organize things.
@rusty-sj we'll be working on that, and would update soon.

**Comment by Shaun-Jonker** [comment]
Thanks guys for this project. I have used a lot of things you have listed to improve my profile
