### ISSUE TITLE
Add more maintainers to the repository

### ISSUE THREAD

**Issue by Hans5958** [abhisheknaiidu/awesome-github-profile-readme#298]
It seems that the repository is inactive and a lot of PR has is stalled due to the inactivity of the maintainer. In that case, should we get new maintainers for this repo?

This is just a suggestion, this doesn't mean that I wanted to be one.

**Comment by abhisheknaiidu** [comment]
@Hans5958 Thanks for opening the issue, I'll try to merge all the PR's in the coming 2 days!!

**Comment by Hans5958** [comment]
Hey, thank you for responding. Good luck handling those pull requests, man.

However, you should consider adding maintainer, probably.
