### ISSUE TITLE
Feature: Add 'all contributors' block to README

### ISSUE THREAD

**Issue by abhisheknaiidu** [abhisheknaiidu/awesome-github-profile-readme#337]
### Is your feature request related to a problem? Please describe.

This is a really nice way to showcase all of our contributors: https://github.com/all-contributors/all-contributors

**Comment by sarthakforwet** [comment]
Hey, the reference repo you gave basically hardcodes all of their contributors in the README file. Do you want the same for this repo or you wanna use the @all-contributors bot mentioned there?

**Comment by abhisheknaiidu** [comment]
@sarthakforwet I want to use  @all-contributors bot for showing just faces of all the contributor's in the last of readme

**Comment by Goldwaage** [comment]
For use @all-contributors the bot have to be installed for the project, as I understand. The installation is documented here: https://allcontributors.org/docs/de/bot/installation
@abhisheknaiidu can you installed the all-contributors bot? Or who will install the bot?

**Comment by abhisheknaiidu** [comment]
Hey @Goldwaage , I've just Installed it

**Comment by Goldwaage** [comment]
Are the last prs of @all-contributors that what this issue want to solve?
