### ISSUE TITLE
Adding Github trophy as a new tool

### ISSUE THREAD

**Issue by Karthik-Nayak98** [abhisheknaiidu/awesome-github-profile-readme#350]
We can add GitHub trophies similar to readme stats. This [link](https://github.com/ryo-ma/github-profile-trophy) will take you to the GitHub page. If you agree I would like to take over this issue.

**Comment by ryo-ma** [comment]
I have already posted a pull request. 
However, this repository has been in a state where pull request merging has been stopped for a long time.
I think should consider adding maintainers.

https://github.com/abhisheknaiidu/awesome-github-profile-readme/pull/289
