### ISSUE TITLE
Feature: Add More Badges 👀

### ISSUE THREAD

**Issue by abhisheknaiidu** [abhisheknaiidu/awesome-github-profile-readme#37]
### Describe the solution you'd like

Add More Badges like `Prettier`, `Continous Integration`

**Comment by ABSphreak** [comment]
I don't think we would need CI/CD in this repo

**Comment by ABSphreak** [comment]
_Check these out:_
### CI Badge
https://github.com/JasonEtco/action-badges#usage
### Prettier Badge
https://github.com/prettier/prettier#badge
