### ISSUE TITLE
Feature: May you add my profile to the list, please? 🥺

### ISSUE THREAD

**Issue by mdccg** [abhisheknaiidu/awesome-github-profile-readme#656]
### Is your feature request related to a problem? Please describe.

Nope!

### Describe the solution you'd like

I would like to add [my profile](https://github.com/mdccg) to the list.

### Describe alternatives you've considered

My profile was written in Portuguese language. If that's a problem, I can translate it.

### Additional context

Watch this divine, resplendent and dazzling [shower of fluffy kittens](https://cat-bounce.com/).

**Comment by nixdonut** [comment]
Make a pull request.

**Comment by sadafamininia99** [comment]
:/

**Comment by abhisheknaiidu** [comment]
@mdccg plz open a PR, we'll look into it.
