### ISSUE TITLE
Feature: List of Oragnization awesome `.github/README.md`

### ISSUE THREAD

**Issue by softmarshmallow** [abhisheknaiidu/awesome-github-profile-readme#709]
Since github now supports `.github/README.md` for organization as their custom profile, it'd be nice to initiate the list in this repo.

I haven't found any other good examples, but here are some few list we can start with

- [`github.com/microsoft`](https://github.com/microsoft) - [`microsoft/.github`](https://github.com/microsoft/.github)

**Comment by abhisheknaiidu** [comment]
@softmarshmallow thanks for raising this, we'll look into this. if you're interested to work on this, feel free to open a PR! 😄

**Comment by softmarshmallow** [comment]
@abhisheknaiidu  I can start from adding few items on this issue, and we can discuss the README location - where & how to place those. :)
