### ISSUE TITLE
Error: Domain awesomegithubprofile.tech expired on 12/09/2021

### ISSUE THREAD

**Issue by alexdelorenzo** [abhisheknaiidu/awesome-github-profile-readme#727]
### Describe the Error

Visiting https://awesomegithubprofile.tech/ resolves to a page that says `This domain name expired on 2021-12-09 23:59:59.` No content is shown.

### Expected behavior

Visiting https://awesomegithubprofile.tech/ should bring users to the intended site with the relevant content.

### Additional context

Cool project!

**Comment by Just-Moh-it** [comment]
It's still available over https://abhisheknaiidu.github.io/awesome-github-profile-readme/ @abhisheknaiidu, it would be great if you could update the link in the repo info.

**Comment by abhisheknaiidu** [comment]
@alexdelorenzo @Just-Moh-it thanks for raising the issue, i've added the url now. 😄
