### ISSUE TITLE
GitHub Sponsors

### ISSUE THREAD

**Issue by APratham** [abhisheknaiidu/awesome-github-profile-readme#75]
Hi.. your profile has GitHub Sponsors link eventhough it is not available in India. Can you please tell how you enrolled into the program? I really want it for one of my projects (currently under development off-GitHub)

**Comment by ABSphreak** [comment]
Hi @APratham,

- GitHub Sponsors link for any project is configured by `funding.yml` inside `.github` folder.
- GitHub Sponsors link for Users is not available in India
- Check [this](https://github.blog/2020-03-24-getting-started-with-github-sponsors/#displayprofile) out for more information.

Don't forget to close the issue! 😊

**Comment by APratham** [comment]
@ABSphreak 

Pardon the confusion, but that still didn't help me understand. What you mean that eventhough it is not generally available, if I configure the `funding.yml` file inside `.github` I should get a Sponsors link for that project?

**Comment by ABSphreak** [comment]
Yes, technically you should.
I don't know the other regulations at GitHub about this, for that you might wanna check out the link that I have mentioned before.

**Comment by APratham** [comment]
Thanks a lot for your help!
