### ISSUE TITLE
Error: The Bit.ly URL is not working properly 

### ISSUE THREAD

**Issue by Abir-Tx** [abhisheknaiidu/awesome-github-profile-readme#791]
### Describe the Error

The provided link in the repository's **About** section is not working.

### Expected behavior

Clicking on the shorten bitly URL should take the user to the deployed page

### Additional context

![Web capture_19-3-2022_165240_bit ly](https://user-images.githubusercontent.com/28858998/159118100-83a6df3b-cb9c-4bdd-9896-034f07118c5c.jpeg)

**Comment by akankshakumari393** [comment]
I tried clicking on the link and that works as expected.
